# Usar imagen base de Nginx
FROM nginx:alpine

# Copiar los archivos HTML y CSS al directorio predeterminado de Nginx
COPY . /usr/share/nginx/html



# Comando de inicio
CMD ["nginx", "-g", "daemon off;"]
